; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.10+4-LPC on Wed Jan 06 2021 14:08:15 GMT+0000 (Greenwich Mean Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


