; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.10+4-LPC on Wed Jan 06 2021 14:08:18 GMT+0000 (Greenwich Mean Time)

