; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.10+4-LPC on Wed Jan 06 2021 14:08:18 GMT+0000 (Greenwich Mean Time)
; Wait for set temperatures to be reached
M116 P0

